# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db67fd92291ba9e6fd09ca373629a39961a26ede0a861db234b006e8d02d857b75575c447c6bed69bc4b087af1e1fc7703a066c203d1dbd7f6ed3b78333b3ea9

test:
  secret_key_base: e71a3d67b5356e0c9dd67edf7b048f91c43e1256177adf2ed9681de8ec2be49a8c06a13b50f75ca942bc7b61c4a59aa760e92de2ba9e9570631a0d552923b26e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
